#Application Configuration
server:
  port: 8092
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never

# To See H2 Console in Browser:
# http://localhost:8092/h2-console
# Enabling H2 Console
spring:
  h2:
    console:
      enabled: true
  # ===============================
  # DB
  # ===============================
  datasource:
    url: jdbc:h2:mem:customerDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:


  # ===============================
  # JPA / HIBERNATE
  # ===============================

  jpa:
#    AÃ±adiendo esta propiedad obviamos el squema de la base de datos
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false
  sql:
    init:
      platform: h2
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
